-- =========================================
-- 1. USER (SUPERTYPE)
-- =========================================
CREATE TABLE users (
    user_id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email                VARCHAR2(100) NOT NULL UNIQUE,
    user_type            VARCHAR2(20) NOT NULL,
    CONSTRAINT chk_user_type
        CHECK (user_type IN ('INDIVIDUAL', 'TRAVEL_AGENT'))
);

-- =========================================
-- 2. USER SUBTYPES
-- =========================================
CREATE TABLE individual_customer (
    user_id NUMBER PRIMARY KEY,
    CONSTRAINT fk_individual_user
        FOREIGN KEY (user_id)
        REFERENCES users(user_id)
        ON DELETE CASCADE
);

CREATE TABLE travel_agent_user (
    user_id NUMBER PRIMARY KEY,
    CONSTRAINT fk_agent_user
        FOREIGN KEY (user_id)
        REFERENCES users(user_id)
        ON DELETE CASCADE
);

-- =========================================
-- 3. PROFILE
-- =========================================
CREATE TABLE profile (
    profile_id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id              NUMBER NOT NULL UNIQUE,
    full_name            VARCHAR2(100) NOT NULL,
    phone_number         VARCHAR2(20),
    travel_preference    VARCHAR2(255),

    CONSTRAINT fk_profile_user
        FOREIGN KEY (user_id)
        REFERENCES users(user_id)
        ON DELETE CASCADE
);

-- =========================================
-- 4. ADDRESS
-- =========================================
CREATE TABLE address (
    address_id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id              NUMBER NOT NULL,
    street               VARCHAR2(255) NOT NULL,
    city                 VARCHAR2(100) NOT NULL,
    province             VARCHAR2(100) NOT NULL,
    postal_code          VARCHAR2(20),
    country              VARCHAR2(100) NOT NULL,

    CONSTRAINT fk_address_user
        FOREIGN KEY (user_id)
        REFERENCES users(user_id)
        ON DELETE CASCADE
);

-- =========================================
-- 5. DESTINATION
-- =========================================
CREATE TABLE destination (
    destination_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    destination_name     VARCHAR2(100) NOT NULL,
    country              VARCHAR2(100) NOT NULL,
    city                 VARCHAR2(100) NOT NULL,
    description          VARCHAR2(500),
    category             VARCHAR2(20) NOT NULL,

    CONSTRAINT chk_destination_category
        CHECK (category IN ('ALAM', 'BUDAYA', 'KULINER'))
);

-- =========================================
-- 6. ATTRACTION
-- =========================================
CREATE TABLE attraction (
    attraction_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    destination_id       NUMBER NOT NULL,
    attraction_name      VARCHAR2(100) NOT NULL,
    description          VARCHAR2(500),

    CONSTRAINT fk_attraction_destination
        FOREIGN KEY (destination_id)
        REFERENCES destination(destination_id)
        ON DELETE CASCADE
);

-- =========================================
-- 7. AGENT
-- =========================================
CREATE TABLE agent (
    agent_id             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_code           VARCHAR2(20) NOT NULL UNIQUE,
    full_name            VARCHAR2(100) NOT NULL,
    performance_rating   NUMBER(3,2),
    work_region          VARCHAR2(100),
    supervisor_id        NUMBER NOT NULL,

    CONSTRAINT fk_agent_supervisor
        FOREIGN KEY (supervisor_id)
        REFERENCES agent(agent_id)
);

-- =========================================
-- 8. TRIP
-- =========================================
CREATE TABLE trip (
    trip_id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id              NUMBER NOT NULL,
    destination_id       NUMBER NOT NULL,
    agent_id             NUMBER NULL,

    departure_date       DATE NOT NULL,
    return_date          DATE NOT NULL,
    trip_status          VARCHAR2(30),
    total_cost           NUMBER(12,2),

    CONSTRAINT fk_trip_user
        FOREIGN KEY (user_id)
        REFERENCES users(user_id),

    CONSTRAINT fk_trip_destination
        FOREIGN KEY (destination_id)
        REFERENCES destination(destination_id),

    CONSTRAINT fk_trip_agent
        FOREIGN KEY (agent_id)
        REFERENCES agent(agent_id)
);

-- =========================================
-- 9. SERVICE (SUPERTYPE)
-- =========================================
CREATE TABLE service (
    service_id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_name         VARCHAR2(100) NOT NULL,
    description          VARCHAR2(500)
);

-- =========================================
-- 10. ACCOMMODATION
-- =========================================
CREATE TABLE accommodation (
    service_id           NUMBER PRIMARY KEY,
    room_type            VARCHAR2(50),
    guest_capacity       NUMBER,
    facilities           VARCHAR2(500),

    CONSTRAINT fk_accommodation_service
        FOREIGN KEY (service_id)
        REFERENCES service(service_id)
        ON DELETE CASCADE
);

-- =========================================
-- 11. TRANSPORTATION
-- =========================================
CREATE TABLE transportation (
    service_id           NUMBER PRIMARY KEY,
    vehicle_type         VARCHAR2(20),
    origin_city          VARCHAR2(100),
    destination_city     VARCHAR2(100),
    service_class        VARCHAR2(20),

    CONSTRAINT fk_transport_service
        FOREIGN KEY (service_id)
        REFERENCES service(service_id)
        ON DELETE CASCADE,

    CONSTRAINT chk_vehicle_type
        CHECK (vehicle_type IN ('PESAWAT', 'BUS', 'KERETA')),

    CONSTRAINT chk_service_class
        CHECK (service_class IN ('EKONOMI', 'BISNIS', 'EKSEKUTIF'))
);

-- =========================================
-- 12. BOOKING
-- =========================================
CREATE TABLE booking (
    booking_id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id              NUMBER NOT NULL,
    service_id           NUMBER NOT NULL,
    booking_date         TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_booking_trip
        FOREIGN KEY (trip_id)
        REFERENCES trip(trip_id)
        ON DELETE CASCADE,

    CONSTRAINT fk_booking_service
        FOREIGN KEY (service_id)
        REFERENCES service(service_id)
);

-- =========================================
-- 13. LOYALCARD
-- =========================================
CREATE TABLE loyalcard (
    card_number          VARCHAR2(30) PRIMARY KEY,
    user_id              NUMBER NOT NULL UNIQUE,
    join_date            DATE NOT NULL,
    membership_level     VARCHAR2(20) NOT NULL,
    reward_points        NUMBER DEFAULT 0,

    CONSTRAINT fk_loyalcard_user
        FOREIGN KEY (user_id)
        REFERENCES individual_customer(user_id)
        ON DELETE CASCADE,

    CONSTRAINT chk_membership_level
        CHECK (membership_level IN ('SILVER', 'GOLD', 'PLATINUM'))
);

-- =========================================
-- 14. PRICE HISTORY
-- =========================================
CREATE TABLE price_history (
    price_history_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_id           NUMBER NOT NULL,
    price                NUMBER(12,2) NOT NULL,
    effective_date       DATE NOT NULL,
    end_date             DATE,

    CONSTRAINT fk_price_service
        FOREIGN KEY (service_id)
        REFERENCES service(service_id)
        ON DELETE CASCADE
);

-- =========================================
-- 15. PAYMENT
-- =========================================
CREATE TABLE payment (
    payment_id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id           NUMBER NOT NULL,
    payment_datetime     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    payment_method       VARCHAR2(30) NOT NULL,
    amount               NUMBER(12,2) NOT NULL,
    payment_status       VARCHAR2(20) NOT NULL,

    CONSTRAINT fk_payment_booking
        FOREIGN KEY (booking_id)
        REFERENCES booking(booking_id)
        ON DELETE CASCADE,

    CONSTRAINT chk_payment_method
        CHECK (payment_method IN (
            'CASH',
            'KARTU_KREDIT',
            'TRANSFER_BANK',
            'E_WALLET'
        )),

    CONSTRAINT chk_payment_status
        CHECK (payment_status IN (
            'TERTUNDA',
            'BERHASIL',
            'GAGAL'
        ))
);

-- =========================================
-- 16. BOOKING STATUS HISTORY
-- =========================================
CREATE TABLE booking_status_history (
    status_history_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id           NUMBER NOT NULL,
    status               VARCHAR2(30) NOT NULL,
    changed_at           TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    sequence_no          NUMBER NOT NULL,

    CONSTRAINT fk_status_booking
        FOREIGN KEY (booking_id)
        REFERENCES booking(booking_id)
        ON DELETE CASCADE,

    CONSTRAINT chk_booking_status
        CHECK (status IN (
            'MENUNGGU_KONFIRMASI',
            'TERKONFIRMASI',
            'SELESAI',
            'DIBATALKAN'
        ))
);
